# Site settings
title: "[ ceej ]"
email: chris@ceej.me.uk
url: https://ceej.me.uk
description: "Personal website for Chris Jordan"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Chris Jordan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
photos:
  - title: flickr
    url: https://www.flickr.com/photos/chrisj
development:
  - title: bitbucket
    url: https://bitbucket.org/theceej
  - title: github
    url: https://github.com/theceej

# Build settings
markdown: kramdown
permalink: pretty
